sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "eSD0Ktj5Jnu7Zn5As0jCRBfoc+R7tOBwQelY5BVZFgAaN8/w3LoNStxJwAGFhBSvyWIzOJX0PK0/ocj4ucxxvuJsWDgHmYz8FfHfqNKivP8cUhrDne4oRiGq5Ml73fWqIZ0l0Z1KwjdinZDBRAmfd71Owyt2JGSO1AxL26Vv34yCuMB7c+Q6U445DS7Znqm1LAbhnbyBo8r02qbJgqWKMAgQ0Q7v1+QuGw5Ti2AS3INW3A5rhow7wTondTUvOdi63UP7rSHoSz7Q1QRdnyomjiEO3iV1DZKcGMdTaPlfmYbNK8w8z7UPZ3i9+cX6VH2XzWFvICg239cYAjPy+C3oBVli31Eh8BNjwe35RMzSDIa+o3FFgtY3iigHv6cObZFbLSpy6STD8L8oEmIknYX9iCNuhAIpsHCXrzJ9Dp320p9h+3rYzQWx8VJLdkv/qVWQtO6/t2ac/xo149K+D5gzsIyeLmMcX/fLqta60CDnZ7rPWRRqlZDtaafKZLG5yBzsZqUe13HZmjeMXMyR9uQguUhU7FRCi2cYqidSbBeqnQ3MbqvmELiS7GCzsCgAxAXG+ez31ZAZ3pR16i5jAKQlufOdmAFB1AzdehDtqhCGZs7ogVptKYshro8L0BR8MA2YQzfRwDkXoRCJ9nvdvbUCFW42IZURUsRhX/Ke6d8vOjc="
cache:
  directories:
    - $HOME/.m2

script:
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always